(()=>{
const config=window.ORLA_LOOK_CONFIG||{},products=window.ORLA_STORE_PRODUCTS||[],stock=window.ORLA_STORE_STOCK||{},compositions=window.ORLA_PRODUCT_COMPOSITIONS||{},BRL=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),img=id=>id&&id.startsWith('assets/')?id:`https://lh3.googleusercontent.com/d/${id}=w1400`;
const entries=(config.refs||[]).map(ref=>({product:products.find(item=>item.ref===ref)})),selected={color:'',size:''};
function bag(){try{return JSON.parse(localStorage.getItem('orla_cart')||'[]')}catch{return[]}}
function variant(entry,code=selected.color){return entry.product?.variants.find(item=>item.code===code)}
function key(ref,code,size){return `${ref}${code}${size}`}
function qty(ref,code,size){return Number(stock[key(ref,code,size)]||0)}
function commonColors(){const first=entries[0]?.product?.variants||[];return first.filter(item=>entries.every(entry=>entry.product?.variants.some(candidate=>candidate.code===item.code&&candidate.img)))}
function commonSizes(code){const variants=entries.map(entry=>variant(entry,code));if(variants.some(item=>!item))return[];return variants[0].sizes.filter(size=>variants.every(item=>item.sizes.includes(size)))}
function availableSizes(code){return commonSizes(code).filter(size=>entries.every(entry=>qty(entry.product.ref,code,size)>0))}
function colorAvailable(code){return availableSizes(code).length>0}
function updateCount(){cartCount.textContent=bag().reduce((sum,item)=>sum+Number(item.quantity||1),0)}
function selectColor(code){selected.color=code;selected.size='';activePhoto=0;draw()}
function selectSize(size){selected.size=size;draw()}
let activePhoto=0;
window.lookPhoto=index=>{activePhoto=index;drawGallery()};window.lookSelectColor=selectColor;window.lookSelectSize=selectSize;
function photos(){const firstVariant=variant(entries[0]);return (firstVariant?.images||[firstVariant?.img]).filter(Boolean).slice(0,2).map((source,index)=>({src:img(source),label:`${config.title} ${index?'costas':'frente'}`}))}
function drawGallery(){const list=photos(),gallery=document.querySelector('.gallery');if(!gallery)return;if(activePhoto>=list.length)activePhoto=0;gallery.innerHTML=`<div class="thumbs">${list.map((photo,index)=>`<button class="thumb ${index===activePhoto?'active':''}" type="button" onclick="lookPhoto(${index})" aria-label="Ver ${photo.label}"><img src="${photo.src}" alt="${photo.label}"></button>`).join('')}</div><div class="main-photo"><img src="${list[activePhoto]?.src||'orla-logo.png'}" alt="${list[activePhoto]?.label||config.title}"></div>`}
function compositionText(){return entries.map(entry=>({name:entry.product?.name,text:compositions[entry.product?.ref]})).filter(item=>item.text).map(item=>`<strong>${item.name}:</strong><br>${item.text.split(' | ').join('<br>')}`).join('<br><br>')||'Composição disponível na etiqueta de cada peça.'}
function draw(){const colors=commonColors();if(!selected.color||!colors.some(item=>item.code===selected.color))selected.color=colors.find(item=>item.code===config.defaultColor)?.code||colors.find(item=>colorAvailable(item.code))?.code||colors[0]?.code||'';const sizes=commonSizes(selected.color),available=availableSizes(selected.color);selected.size=available.includes(selected.size)?selected.size:(available[0]||'');const variants=entries.map(entry=>variant(entry)),total=variants.reduce((sum,item)=>sum+Number(item?.price||0),0),currentColor=variants[0]?.color||'',setAvailable=Boolean(selected.color&&available.length&&variants.every(Boolean));lookProduct.innerHTML=`<div class="gallery"></div><section class="details"><div class="eyebrow">Biquíni · ${config.collection}</div><h1>${config.title}</h1><div class="reference">Referência: ${config.displayRef}</div><div class="price">${BRL(total)}</div><div class="color">Cor ou estampa: <b>${currentColor||'Indisponível'}</b></div><div class="colors">${colors.map(item=>`<button type="button" onclick="lookSelectColor('${item.code}')" class="${selected.color===item.code?'active':''}">${item.color}${colorAvailable(item.code)?'':' · indisponível'}</button>`).join('')}</div><div class="size-label">Tamanho do conjunto: <b>${selected.size||'Indisponível'}</b></div><div class="sizes">${sizes.map(size=>`<button type="button" onclick="lookSelectSize('${size}')" class="${selected.size===size?'active':''}" ${available.includes(size)?'':'disabled'}>${size}</button>`).join('')}</div><button id="addLook" class="add-look" type="button" ${setAvailable&&selected.size?'':'disabled'}>${setAvailable?'Adicionar as 2 peças à sacola':'Conjunto indisponível'}</button><div class="availability">${setAvailable?'Disponível para pronta entrega':'Conjunto indisponível no estoque'}</div><div class="status" id="lookStatus" role="status" aria-live="polite"></div><div class="accordion"><details open><summary>Sobre a peça</summary><p>Conjunto ORLA da coleção ${config.collection}, formado por ${entries.map(entry=>entry.product?.name).filter(Boolean).join(' e ')}. As duas peças são selecionadas na mesma cor ou estampa e no mesmo tamanho.</p></details><details><summary>Composição e cuidados</summary><p>${compositionText()}<br><br><strong>Cuidados:</strong><br>Lavar à mão, com sabão neutro e água fria. Secar à sombra. Não usar alvejante e não guardar as peças úmidas.</p></details><details><summary>Trocas e devoluções</summary><p>Consulte a <a href="trocas-e-devolucoes.html">política de trocas e devoluções da ORLA</a> para prazos, condições e orientações.</p></details></div></section>`;drawGallery();document.getElementById('addLook')?.addEventListener('click',addToBag)}
function addToBag(){const current=bag();for(const entry of entries){const item=variant(entry),sku=key(entry.product.ref,selected.color,selected.size),inBag=current.filter(row=>row.sku===sku).reduce((sum,row)=>sum+Number(row.quantity||1),0);if(!item||!selected.size||inBag>=qty(entry.product.ref,selected.color,selected.size)){lookStatus.textContent='Uma das peças não possui mais a quantidade necessária.';return}current.push({sku,ref:entry.product.ref,name:entry.product.name,color:item.color,size:selected.size,price:item.price,quantity:1,img:item.img})}localStorage.setItem('orla_cart',JSON.stringify(current));updateCount();lookStatus.innerHTML='Conjunto adicionado à sacola. <a href="checkout.html">Ver a sacola</a>'}
updateCount();draw();
})();
